name: Build and Deploy

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      bucket:
        required: true
        type: string
      aws_region:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Angular application
      run: npm run build --prod

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: prod-artifacts
        path: dist/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws_region }}

    - name: Sync S3 bucket
      run: aws s3 sync dist/ s3://${{ inputs.bucket }} --delete

    - name: Notify deployment
      if: always()
      run: echo "Deployment to ${{ inputs.stage }} stage complete."
