name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - stage-name: dev
            artifact: basic-app-dev
            aws_region: us-east-1
          - stage-name: qa
            artifact: basic-app-qa
            aws_region: us-west-1
          - stage-name: prod
            artifact: basic-app-prod
            aws_region: eu-central-1s

    steps:
      - name: Build
        uses: ./../.github/workflows/build.yml
    