name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - stage-name: dev
            artifact: basic-app-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in the repository
        run: ls -a

      - name: Print workflow metadata
        run: |
          echo "Workflow name: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Job name: ${{ github.job }}"

      - name: Build
        uses: ./../.github/workflows/action.yml
        with:
          stage: ${{ matrix.stage-name }}
          artifact: ${{ matrix.artifact }}
          