name: CI/CD for Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [dev, qa, prod]
        include:
          - stage: dev
            bucket: your-dev-s3-bucket
            aws_region: us-east-1
          - stage: qa
            bucket: your-qa-s3-bucket
            aws_region: us-west-1
          - stage: prod
            bucket: your-prod-s3-bucket
            aws_region: eu-central-1

    steps:
    - name: Call reusable workflow
      uses: ./.github/workflows/build.yml@main
      with:
        stage: ${{ matrix.stage }}
        bucket: ${{ matrix.bucket }}
        aws_region: ${{ matrix.aws_region }}
