name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - stage-name: dev
            artifact: basic-app-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: ./action.yml
        with:
          stage: ${{ matrix.stage-name }}
          artifact: ${{ matrix.artifact }}
          