name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - stage-name: dev
            artifact: basic-app-dev
          - stage-name: qa
            artifact: basic-app-qa
          - stage-name: prod
            artifact: basic-app-prod

    steps:
      - name: Build
        uses: ./.github/workflows/build.yml@main
        with:
          stage: ${{ matrix.stage-name }}
          artifact: ${{ matrix.artifact }}
    