name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: tomar12akshay/basic-app/.github/workflows/build.yml@main
    if: github.ref == 'refs/heads/develop'
    with:
      stage: dev
      artifact: basic-dev
          